# Base application configuration for Microswitch
# This file provides default values for the InitializerConfiguration bean
# bound with prefix: "microswitch" (see com.microswitch.domain.InitializerConfiguration)

microswitch:
  # Master switch for the library. If false, all strategies are disabled by default.
  enabled: false
  # Enable/disable detailed logging of service key, strategy, and method execution.
  # When enabled, logs which service, strategy, and method (primary/secondary) are being executed.
  # Default: disable (no detailed execution logging)
  logger: disable

  # Map of service configurations by service key/name.
  # Replace example keys (order-service, payment-service) with your actual service identifiers.
  services:
    order-service:
      enabled: true
      # Active deployment strategy for this service (canary, shadow, blueGreen)
      activeStrategy: canary
      canary:
        # Percentage of traffic going to the primary (stable) version in canary deployment.
        # Remaining percentage goes to the canary version.
        percentage: 10/90
        # Algorithm determining how canary routing is selected. Defaults to SEQUENCE.
        # Other supported values must match AlgorithmType enum values.
        algorithm: sequential
      blueGreen:
        # Percentage of traffic for the primary (blue or green) environment.
        weight: 1/0
        # Time-to-live in milliseconds for session stickiness or route persistence (if applicable).
        ttl: 60000
      shadow:
        stable: primary
        mirror: secondary
        mirrorPercentage: 10
        # Enable/disable deep object comparison for shadow traffic validation.
        # When enabled, compares objects by field values rather than reference equality.
        # Default: disable (uses standard equals() method)
        comparator: disable

# You can override any of these values per environment using Spring profiles,
# e.g., create application-dev.yml and application-prod.yml and place overrides there.