# Base application configuration for Microswitch
# This file provides default values for the InitializerConfiguration bean
# bound with prefix: "microswitch" (see com.microswitch.domain.InitializerConfiguration)

microswitch:
  # Master switch for the library. If false, all strategies are disabled by default.
  enabled: true

  # Map of service configurations by service key/name.
  # Replace example keys (order-service, payment-service) with your actual service identifiers.
  services:
    order-service:
      enabled: true
      canary:
        # Percentage of traffic going to the primary (stable) version in canary deployment.
        # Remaining percentage goes to the canary version.
        primaryPercentage: 90
        # Algorithm determining how canary routing is selected. Defaults to SEQUENCE.
        # Other supported values must match AlgorithmType enum values.
        algorithm: SEQUENCE
      blueGreen:
        # Percentage of traffic for the primary (blue or green) environment.
        weight: 1/0
        # Time-to-live in milliseconds for session stickiness or route persistence (if applicable).
        ttl: 60000
      shadow:
        # Weight for shadow traffic mirroring. Short (0-100 recommended range depending on implementation).
        weight: 10

    payment-service:
      enabled: false
      canary:
        primaryPercentage: 95
        algorithm: SEQUENCE
      blueGreen:
        primaryPercentage: 100
        ttl: 120000
      shadow:
        weight: 0

# You can override any of these values per environment using Spring profiles,
# e.g., create application-dev.yml and application-prod.yml and place overrides there.