# Base application configuration for Microswitch
# This file provides default values for the InitializerConfiguration bean
# bound with prefix: "microswitch" (see com.microswitch.domain.InitializerConfiguration)

microswitch:
  # Master switch for the library. If false, all strategies are disabled by default.
  enabled: false
  # Enable/disable detailed logging of service key, strategy, and method execution.
  # When enabled, logs which service, strategy, and method (primary/secondary) are being executed.
  # Default: disable (no detailed execution logging)
  logger: disable

  # Map of service configurations by service key/name.
  # Replace example keys (order-service, payment-service) with your actual service identifiers.
  services:
    order-service:
      enabled: true
      # Active deployment strategy for this service (canary, shadow, blueGreen)
      activeStrategy: canary
      canary:
        # Percentage of traffic going to the primary (stable) version in canary deployment.
        # Remaining percentage goes to the canary version.
        percentage: 10/90
        # Algorithm determining how canary routing is selected. Defaults to SEQUENCE.
        # Other supported values must match AlgorithmType enum values.
        algorithm: sequential
      blueGreen:
        # Percentage of traffic for the primary (blue or green) environment.
        weight: 1/0
        # Time-to-live in milliseconds for session stickiness or route persistence (if applicable).
        ttl: 60000
      shadow:
        stable: primary
        mirror: secondary
        # Legacy name retained for backward compatibility with InitializerConfiguration setters
        mirrorPercentage: 10
        # Deep comparison configuration. When enabled, objects are compared by field values.
        comparator:
          # enable | disable (case-insensitive). Legacy single-line `comparator: enable` also supported.
          mode: disable
          # If a list size exceeds this threshold, sampler mode is activated instead of full scan.
          maxCollectionElements: 10000
          # Hard time budget for comparison in milliseconds. Exceeding returns early with WARN log.
          maxCompareTimeMillis: 200
          # When true, activates sampling for very large lists to avoid O(n) full scan cost.
          enableSamplingOnHuge: true
          # Sampling step used in stride sampling (every Nth element is compared).
          stride: 100
          # Cap the number of reflected fields per class considered during deep comparison.
          # Hard cap: 100 (values above 100 are clamped at runtime)
          maxFieldsPerClass: 100

# You can override any of these values per environment using Spring profiles,
# e.g., create application-dev.yml and application-prod.yml and place overrides there.