name: Publish to GitHub Packages

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GPR_OWNER: ${{ github.repository_owner }}
      # Extract repo name from owner/repo
      GPR_REPO: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: 'github'                   # matches distributionManagement <id>
          server-username: GITHUB_ACTOR         # env var provided by Actions
          server-password: GITHUB_TOKEN         # env var provided by Actions

      - name: Build and publish
        run: |
          mvn -B -DskipTests \
            -Dgpr.owner=${GPR_OWNER} \
            -Dgpr.repo=${GPR_REPO} \
            clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
